# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='author',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
